[fa]
  title = "علیرضا یونسی - L'instit"
  languageName = "فارسی"
  weight = 2
  contentdir = "content/fa"

[en]
  title = "Alireza Yoonesi - L'instit"
  languageName = "English"
  weight = 1
  contentdir = "content/en"
