Description = "My Blog, Wehre I talk; For in much wisdom is much vexation, and he who increases knowledge increases sorrow."
Keywords =  "Blog, Software, Big Data, Programming, Python, Machine Learning, Data Science"
Subtitle = "My Blog & Other Stuff"
AuthorImg = "/img/me.png"
AuthorName = "Alireza Yoonesi"
Introduce = "For in much wisdom is much vexation, and he who increases knowledge increases sorrow."
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"

ArticleDecContent = "This blog post article is under the <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a> license,Please indicate the source!"

[Footer]
  StorageLink = "https://www.Cloudflare.com"
  StorageName = "CloudFlare"
  ICPLink = "https://github.com/AYoonesi/AYoonesi.github.io"
  ICPNo = "GithHub Repository"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/AYoonesi/"

[[Socials]]
  Name = "Instagram"
  Icon = "globe"
  URL = "https://instagram.com/_alireza.yoonesi"

[[Links]]
  Name = "Paracurve"
  Permalink = "http://paracurve.com/"

[[Links]]
  Name = "Financial Times"
  Permalink = "https://www.ft.com/"

[[Links]]
  Name = "The Economist"
  Permalink = "https://www.economist.com/"

[[Links]]
  Name = "Library Genesis"
  Permalink = "http://libgen.rs/"

[[Links]]
  Name = "LibGen+"
  Permalink = "https://libgen.li/"